package main

import (
	"context"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"

	"lets_config/config"
	"lets_config/internal/builder"
	wailsRuntime "github.com/wailsapp/wails/v2/pkg/runtime"
)

// App struct
type App struct {
	ctx     context.Context
	Config  *config.Manager
	Builder *builder.Builder
}

// NewApp creates a new App application struct.
func NewApp(cfg *config.Manager) *App {
	appData := filepath.Join(os.Getenv("APPDATA"), "unieditdept", "foil")

	return &App{
		Config: cfg,
		Builder: builder.New(
			filepath.Join("assets", "foil-example.apk"), // template APK
			filepath.Join(os.Getenv("USERPROFILE"), "Desktop"), // default output: desktop
			filepath.Join(appData, "keys"),
			filepath.Join(appData, "builds"),
		),
	}
}

// startup is called when the app starts. The context is saved
// so we can call the runtime methods.
func (a *App) startup(ctx context.Context) {
	a.ctx = ctx
}

// SelectDirectory opens a native folder picker and returns the selected path.
func (a *App) SelectDirectory() string {
	dir, err := wailsRuntime.OpenDirectoryDialog(a.ctx, wailsRuntime.OpenDialogOptions{
		Title: "选择 HTML 项目文件夹",
	})
	if err != nil || dir == "" {
		return ""
	}
	return dir
}

// SelectFile opens a native file picker and returns the selected file path.
func (a *App) SelectFile() string {
	file, err := wailsRuntime.OpenFileDialog(a.ctx, wailsRuntime.OpenDialogOptions{
		Title: "选择 HTML/ZIP 文件",
		Filters: []wailsRuntime.FileFilter{
			{DisplayName: "支持的文件", Pattern: "*.zip;*.html;*.htm"},
		},
	})
	if err != nil || file == "" {
		return ""
	}
	return file
}

// BuildAPK runs the full build pipeline. Called from frontend via Wails bind.
// projectDir: path to HTML project folder.
// appName: user-visible app name.
// icons: map of icon path -> webp bytes (generated by frontend canvas).
func (a *App) BuildAPK(projectDir, appName string, iconsBase64 map[string]string) (*builder.BuildResult, error) {
	icons := make(map[string][]byte, len(iconsBase64))
	for path, b64 := range iconsBase64 {
		data, err := base64.StdEncoding.DecodeString(b64)
		if err != nil {
			return nil, fmt.Errorf("icon %s: %w", path, err)
		}
		icons[path] = data
	}
	return a.Builder.Build(builder.BuildInput{
		ProjectDir: projectDir,
		AppName:    appName,
		IconWebP:   icons,
	})
}

// GetIconPaths returns the list of icon files needed.
func (a *App) GetIconPaths() []string {
	return builder.IconPaths()
}

// GeneratePackageName auto-generates a unique package name.
func (a *App) GeneratePackageName(appName string) string {
	return builder.GeneratePackageName(appName, nil, 26)
}

// GetConfig returns the full application configuration.
func (a *App) GetConfig() (*config.Config, error) {
	return a.Config.Get(), nil
}

// SaveConfig persists the full application configuration.
func (a *App) SaveConfig(cfg config.Config) error {
	return a.Config.Update(func(c *config.Config) error {
		*c = cfg
		return nil
	})
}
