package main

import (
	"context"
	"os"
	"path/filepath"

	"lets_config/config"
	"lets_config/internal/builder"
)

// App struct
type App struct {
	ctx     context.Context
	Config  *config.Manager
	Builder *builder.Builder
}

// NewApp creates a new App application struct.
func NewApp(cfg *config.Manager) *App {
	appData := filepath.Join(os.Getenv("APPDATA"), "unieditdept", "foil")

	return &App{
		Config: cfg,
		Builder: builder.New(
			filepath.Join("assets", "foil-example.apk"), // template APK
			filepath.Join(os.Getenv("USERPROFILE"), "Desktop"), // default output: desktop
			filepath.Join(appData, "keys"),
			filepath.Join(appData, "builds"),
		),
	}
}

// startup is called when the app starts. The context is saved
// so we can call the runtime methods.
func (a *App) startup(ctx context.Context) {
	a.ctx = ctx
}

// BuildAPK runs the full build pipeline. Called from frontend via Wails bind.
// projectDir: path to HTML project folder.
// appName: user-visible app name.
// icons: map of icon path -> webp bytes (generated by frontend canvas).
func (a *App) BuildAPK(projectDir, appName string, icons map[string][]byte) (*builder.BuildResult, error) {
	return a.Builder.Build(builder.BuildInput{
		ProjectDir: projectDir,
		AppName:    appName,
		IconWebP:   icons,
	})
}

// GetIconPaths returns the list of icon files needed.
func (a *App) GetIconPaths() []string {
	return builder.IconPaths()
}

// GeneratePackageName auto-generates a unique package name.
func (a *App) GeneratePackageName(appName string) string {
	return builder.GeneratePackageName(appName, nil, 26)
}

// GetConfig returns the full application configuration.
func (a *App) GetConfig() (*config.Config, error) {
	return a.Config.Get(), nil
}

// SaveConfig persists the full application configuration.
func (a *App) SaveConfig(cfg config.Config) error {
	return a.Config.Update(func(c *config.Config) error {
		*c = cfg
		return nil
	})
}
