package main

import (
	"archive/zip"
	"context"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"lets_config/config"
	"lets_config/internal/builder"
	wailsRuntime "github.com/wailsapp/wails/v2/pkg/runtime"
)

// App struct
type App struct {
	ctx     context.Context
	Config  *config.Manager
	Builder *builder.Builder
}

// NewApp creates a new App application struct.
func NewApp(cfg *config.Manager) *App {
	appData := filepath.Join(os.Getenv("APPDATA"), "unieditdept", "foil")

	return &App{
		Config: cfg,
		Builder: builder.New(
			filepath.Join("assets", "foil-example.apk"), // template APK
			filepath.Join(os.Getenv("USERPROFILE"), "Desktop"), // default output: desktop
			filepath.Join(appData, "keys"),
			filepath.Join(appData, "builds"),
		),
	}
}

// startup is called when the app starts. The context is saved
// so we can call the runtime methods.
func (a *App) startup(ctx context.Context) {
	a.ctx = ctx
}

// SelectDirectory opens a native folder picker and returns the selected path.
func (a *App) SelectDirectory() string {
	dir, err := wailsRuntime.OpenDirectoryDialog(a.ctx, wailsRuntime.OpenDialogOptions{
		Title: "选择 HTML 项目文件夹",
	})
	if err != nil || dir == "" {
		return ""
	}
	return dir
}

// SelectFile opens a native file picker and returns the selected file path.
func (a *App) SelectFile() string {
	file, err := wailsRuntime.OpenFileDialog(a.ctx, wailsRuntime.OpenDialogOptions{
		Title: "选择 HTML/ZIP 文件",
		Filters: []wailsRuntime.FileFilter{
			{DisplayName: "支持的文件", Pattern: "*.zip;*.html;*.htm"},
		},
	})
	if err != nil || file == "" {
		return ""
	}
	return file
}

// TempDirBase returns the base directory for temporary files:
// %TEMP%\unieditdept\foil\
func TempDirBase() string {
	return filepath.Join(os.TempDir(), "unieditdept", "foil")
}

// PrepareFileInput converts a file path (.html or .zip) into a usable
// project directory. For .html it copies the file as index.html in a temp
// dir; for .zip it extracts to a temp directory.
func (a *App) PrepareFileInput(filePath string) (string, error) {
	base := TempDirBase()
	os.MkdirAll(base, 0755) // ensure base dir exists
	lower := strings.ToLower(filePath)

	if strings.HasSuffix(lower, ".html") || strings.HasSuffix(lower, ".htm") {
		tmpDir, err := os.MkdirTemp(base, "html-*")
		if err != nil {
			return "", fmt.Errorf("create temp dir: %w", err)
		}
		dest := filepath.Join(tmpDir, "index.html")
		src, err := os.Open(filePath)
		if err != nil {
			os.RemoveAll(tmpDir)
			return "", fmt.Errorf("open html: %w", err)
		}
		defer src.Close()
		out, err := os.Create(dest)
		if err != nil {
			os.RemoveAll(tmpDir)
			return "", fmt.Errorf("create index.html: %w", err)
		}
		defer out.Close()
		if _, err := io.Copy(out, src); err != nil {
			os.RemoveAll(tmpDir)
			return "", fmt.Errorf("copy html: %w", err)
		}
		return tmpDir, nil
	}

	if strings.HasSuffix(lower, ".zip") {
		tmpDir, err := os.MkdirTemp(base, "zip-*")
		if err != nil {
			return "", fmt.Errorf("create temp dir: %w", err)
		}
		r, err := zip.OpenReader(filePath)
		if err != nil {
			os.RemoveAll(tmpDir)
			return "", fmt.Errorf("open zip: %w", err)
		}
		defer r.Close()

		for _, f := range r.File {
			fpath := filepath.Join(tmpDir, f.Name)
			if f.FileInfo().IsDir() {
				os.MkdirAll(fpath, 0755)
				continue
			}
			os.MkdirAll(filepath.Dir(fpath), 0755)
			rc, err := f.Open()
			if err != nil {
				return "", fmt.Errorf("open %s: %w", f.Name, err)
			}
			out, err := os.OpenFile(fpath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, f.Mode())
			if err != nil {
				rc.Close()
				return "", fmt.Errorf("create %s: %w", fpath, err)
			}
			_, err = io.Copy(out, rc)
			rc.Close()
			out.Close()
			if err != nil {
				return "", fmt.Errorf("write %s: %w", f.Name, err)
			}
		}
		return tmpDir, nil
	}

	return "", fmt.Errorf("unsupported file type: %s", filePath)
}

// BuildAPK runs the full build pipeline. Called from frontend via Wails bind.
// projectDir: path to HTML project folder.
// appName: user-visible app name.
// packageName: optional custom package name; empty = auto-generate.
// versionName: optional version name (digits and dots); empty = auto-generate.
// icons: map of icon path -> webp bytes (generated by frontend canvas).
func (a *App) BuildAPK(projectDir, appName, packageName, versionName string, iconsBase64 map[string]string) (*builder.BuildResult, error) {
	icons := make(map[string][]byte, len(iconsBase64))
	for path, b64 := range iconsBase64 {
		data, err := base64.StdEncoding.DecodeString(b64)
		if err != nil {
			return nil, fmt.Errorf("icon %s: %w", path, err)
		}
		icons[path] = data
	}
	// Track temp dirs from PrepareFileInput for automatic cleanup
	if strings.HasPrefix(projectDir, TempDirBase()) {
		a.Builder.TrackTempDir(projectDir)
	}
	return a.Builder.Build(builder.BuildInput{
		ProjectDir:  projectDir,
		AppName:     appName,
		PackageName: packageName,
		VersionName: versionName,
		IconWebP:    icons,
	})
}

// GetIconPaths returns the list of icon files needed.
func (a *App) GetIconPaths() []string {
	return builder.IconPaths()
}

// GeneratePackageName auto-generates a unique package name.
func (a *App) GeneratePackageName(appName string) string {
	return builder.GeneratePackageName(appName, nil, 26)
}

// GetConfig returns the full application configuration.
func (a *App) GetConfig() (*config.Config, error) {
	return a.Config.Get(), nil
}

// SaveConfig persists the full application configuration.
func (a *App) SaveConfig(cfg config.Config) error {
	return a.Config.Update(func(c *config.Config) error {
		*c = cfg
		return nil
	})
}
