// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildAPK(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BuildAPK'](arg1, arg2, arg3, arg4, arg5);
}

export function GeneratePackageName(arg1) {
  return window['go']['main']['App']['GeneratePackageName'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetIconPaths() {
  return window['go']['main']['App']['GetIconPaths']();
}

export function ListKeystoreAliases(arg1, arg2) {
  return window['go']['main']['App']['ListKeystoreAliases'](arg1, arg2);
}

export function LoadCertInfo() {
  return window['go']['main']['App']['LoadCertInfo']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PrepareFileInput(arg1) {
  return window['go']['main']['App']['PrepareFileInput'](arg1);
}

export function SaveCertInfo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveCertInfo'](arg1, arg2, arg3, arg4);
}

export function SetCustomCert(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetCustomCert'](arg1, arg2, arg3, arg4);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectCertFile() {
  return window['go']['main']['App']['SelectCertFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}
