// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {builder} from '../models';
import {config} from '../models';
import {main} from '../models';

export function BuildAPK(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>):Promise<builder.BuildResult>;

export function GeneratePackageName(arg1:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetIconPaths():Promise<Array<string>>;

export function ListKeystoreAliases(arg1:string,arg2:string):Promise<Array<string>>;

export function LoadCertInfo():Promise<main.CertInfo | null>;

export function OpenFolder(arg1:string):Promise<void>;

export function PrepareFileInput(arg1:string):Promise<string>;

export function SaveCertInfo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectCertFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectOutputDir():Promise<string>;

export function SetCustomCert(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
