// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {builder} from '../models';
import {config} from '../models';

export function BuildAPK(arg1:string,arg2:string,arg3:Record<string, Array<number>>):Promise<builder.BuildResult>;

export function GeneratePackageName(arg1:string):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetIconPaths():Promise<Array<string>>;

export function SaveConfig(arg1:config.Config):Promise<void>;
