// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildAPK(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildAPK'](arg1, arg2, arg3);
}

export function GeneratePackageName(arg1) {
  return window['go']['main']['App']['GeneratePackageName'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetIconPaths() {
  return window['go']['main']['App']['GetIconPaths']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
